# -*- coding: utf-8 -*-
"""Banking Management System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SyQ7XKIJO29FurbLot85I-XqsT7EBu78
"""

import random
import json
import os

bank_data = {}

names_20 = [
    "Aarav Sharma", "Vivaan Gupta", "Aditya Kumar", "Vihaan Singh",
    "Arjun Reddy", "Sai Patel", "Kunal Madan", "Rahul Verma",
    "Priya Mehta", "Ananya Sharma", "Diya Patel", "Kavya Singh",
    "Riya Reddy", "Sara Khan", "Isha Gupta", "Aisha Kumar",
    "Neha Singh", "Pooja Sharma", "Meera Reddy", "Sneha Patel"
]


def save_data():
    """Save all data to file"""
    try:
        with open('bank_data.json', 'w') as f:
            json.dump(bank_data, f)
        print(" Data saved successfully!")
        return True
    except:
        print(" Error saving data!")
        return False

def load_data():
    """Load data from file"""
    global bank_data
    try:
        with open('bank_data.json', 'r') as f:
            bank_data = json.load(f)
        print(f"Data loaded! {len(bank_data)} customers found.")
        return True
    except FileNotFoundError:
        print(" No saved data found. Starting fresh...")
        return False
    except:
        print("Error loading data!")
        return False

def create_20_customers():
    """Auto create 20 customers"""
    global bank_data

    if bank_data:
        print(f"Data already exists! {len(bank_data)} customers present.")
        return

    bank_data = {}

    for i in range(20):
        acc_id = str(101 + i)
        balance = random.randint(1000, 50000)
        bank_data[acc_id] = {
            "name": names_20[i],
            "balance": balance
        }

    print("=" * 50)
    print(" 20 CUSTOMERS CREATED")
    print("=" * 50)
    print(f"  Account IDs: 101 to 120")
    print(f"  Total: {len(bank_data)} customers")
    print("=" * 50)

def show_menu():
    print("\n" + "=" * 50)
    print("        BANKING SYSTEM")
    print("=" * 50)
    print("  1. Create Account")
    print("  2. Deposit")
    print("  3. Withdraw")
    print("  4. Check Balance")
    print("  5. All Accounts")
    print("  6. Show 20 Customers")
    print("  7. Transfer Money")
    print("  8. Delete Account")
    print("  9. Save Data")
    print("  10. Exit")
    print("=" * 50)


def create_account():
    """1. Create new account"""
    print("\n--- CREATE ACCOUNT ---")

    if not bank_data:
        acc_id = "101"
    else:
        acc_id = str(max(int(x) for x in bank_data.keys()) + 1)

    print(f"Your Account ID: {acc_id}")
    name = input("Enter Name: ").strip()

    while True:
        try:
            bal = float(input("Initial Deposit (min ₹1000): "))
            if bal >= 1000:
                break
            print("Minimum ₹1000 required!")
        except:
            print("Enter valid number!")

    bank_data[acc_id] = {"name": name, "balance": bal}
    print(f"\n Account created! ID: {acc_id}\n")

def deposit():
    """2. Deposit money"""
    print("\n--- DEPOSIT ---")
    acc_id = input("Account ID: ").strip()

    if acc_id not in bank_data:
        print("Account not found!")
        print(f"   Available IDs: 101 to {max(bank_data.keys())}")
        return

    while True:
        try:
            amt = float(input("Amount: "))
            if amt > 0:
                break
            print("Amount must be positive!")
        except:
            print("Enter valid number!")

    bank_data[acc_id]["balance"] += amt
    print(f"₹{amt:,.2f} deposited!")
    print(f"New Balance: ₹{bank_data[acc_id]['balance']:,.2f}\n")

def withdraw():
    """3. Withdraw money"""
    print("\n--- WITHDRAW ---")
    acc_id = input("Account ID: ").strip()

    if acc_id not in bank_data:
        print("Account not found!")
        print(f"   Available IDs: 101 to {max(bank_data.keys())}")
        return

    curr_bal = bank_data[acc_id]["balance"]
    print(f"Current Balance: ₹{curr_bal:,.2f}")

    while True:
        try:
            amt = float(input("Amount: "))
            if amt <= 0:
                print("Amount must be positive!")
                continue
            if amt > curr_bal:
                print(f"Insufficient! Max: ₹{curr_bal:,.2f}")
                continue
            break
        except:
            print("Enter valid number!")

    bank_data[acc_id]["balance"] -= amt
    print(f"₹{amt:,.2f} withdrawn!")
    print(f"Remaining: ₹{bank_data[acc_id]['balance']:,.2f}\n")

def check_balance():
    """4. Check balance"""
    print("\n--- CHECK BALANCE ---")
    acc_id = input("Account ID: ").strip()

    if acc_id not in bank_data:
        print("Account not found!")
        print(f"   Available IDs: 101 to {max(bank_data.keys())}")
        return

    d = bank_data[acc_id]
    print(f"\n  Account ID: {acc_id}")
    print(f"  Name: {d['name']}")
    print(f"  Balance: ₹{d['balance']:,.2f}\n")

def show_all():
    """5. Show all accounts"""
    print("\n--- ALL ACCOUNTS ---")

    if not bank_data:
        print("No accounts found!\n")
        return

    print("-" * 50)
    print(f"{'ID':<8} {'Name':<25} {'Balance':>15}")
    print("-" * 50)

    total = 0
    for acc_id, d in bank_data.items():
        print(f"{acc_id:<8} {d['name']:<25} ₹{d['balance']:>12,.2f}")
        total += d['balance']

    print("-" * 50)
    print(f"TOTAL: {len(bank_data)} customers")
    print(f"TOTAL BALANCE: ₹{total:,.2f}")
    print("-" * 50 + "\n")

def show_20_customers():
    """6. Show all 20 customers"""
    print("\n--- ALL 20 CUSTOMERS ---")
    print("-" * 55)
    print(f"{'ID':<8} {'Name':<25} {'Balance':>20}")
    print("-" * 55)

    for acc_id, d in bank_data.items():
        print(f"{acc_id:<8} {d['name']:<25} ₹{d['balance']:>18,.2f}")

    print("-" * 55)
    total = sum(d['balance'] for d in bank_data.values())
    print(f"TOTAL: {len(bank_data)} customers")
    print(f"TOTAL BALANCE: ₹{total:,.2f}")
    print("-" * 55 + "\n")

def transfer_money():
    """7. Transfer money between accounts - NEW"""
    print("\n--- TRANSFER MONEY ---")

    from_acc = input("From Account ID: ").strip()

    if from_acc not in bank_data:
        print(" Source account not found!")
        print(f"   Available IDs: 101 to {max(bank_data.keys())}")
        return

    to_acc = input("To Account ID: ").strip()

    if to_acc not in bank_data:
        print(" Destination account not found!")
        print(f"   Available IDs: 101 to {max(bank_data.keys())}")
        return

    if from_acc == to_acc:
        print("Cannot transfer to same account!")
        return

    curr_bal = bank_data[from_acc]["balance"]
    print(f"\nSource: {bank_data[from_acc]['name']}")
    print(f"Balance: ₹{curr_bal:,.2f}")

    while True:
        try:
            amt = float(input("\nAmount to transfer: "))
            if amt <= 0:
                print("Amount must be positive!")
                continue
            if amt > curr_bal:
                print(f"Insufficient! Max: ₹{curr_bal:,.2f}")
                continue
            break
        except:
            print("Enter valid number!")

    bank_data[from_acc]["balance"] -= amt
    bank_data[to_acc]["balance"] += amt

    print(f"\n ₹{amt:,.2f} transferred successfully!")
    print(f"   From: {bank_data[from_acc]['name']}")
    print(f"   To: {bank_data[to_acc]['name']}")
    print(f"   New Source Balance: ₹{bank_data[from_acc]['balance']:,.2f}\n")

def delete_account():
    """8. Delete account - NEW"""
    print("\n--- DELETE ACCOUNT ---")
    acc_id = input("Account ID to delete: ").strip()

    if acc_id not in bank_data:
        print("Account not found!")
        print(f"   Available IDs: 101 to {max(bank_data.keys())}")
        return

    print(f"\nAccount Details:")
    print(f"  Name: {bank_data[acc_id]['name']}")
    print(f"  Balance: ₹{bank_data[acc_id]['balance']:,.2f}")

    confirm = input("\nAre you sure you want to delete? (y/n): ").lower()

    if confirm == 'y':
        del bank_data[acc_id]
        print("Account deleted successfully!")
    else:
        print("Deletion cancelled!")

    print()


def main():
    """Main menu"""

    if not load_data():
        create_20_customers()

    while True:
        show_menu()
        choice = input("Enter choice (1-10): ").strip()

        if choice == '1':
            create_account()
        elif choice == '2':
            deposit()
        elif choice == '3':
            withdraw()
        elif choice == '4':
            check_balance()
        elif choice == '5':
            show_all()
        elif choice == '6':
            show_20_customers()
        elif choice == '7':
            transfer_money()
        elif choice == '8':
            delete_account()
        elif choice == '9':
            save_data()
        elif choice == '10':
            save_data()
            print("\n Thank you! \n")
            break
        else:
            print(" Invalid! Enter 1-10 only.\n")

        input("Press Enter to continue...")

if __name__ == "__main__":
    main()

import pandas as pd
import json
import os

if 'bank_data' not in globals():
    print("Variable 'bank_data' not found. Attempting to load from 'bank_data.json'...")
    try:
        with open('bank_data.json', 'r') as f:
            bank_data = json.load(f)
        print(f"Loaded {len(bank_data)} customers from 'bank_data.json'.")
    except FileNotFoundError:
        print("Warning: 'bank_data.json' not found. Initializing 'bank_data' as empty.")
        bank_data = {}
    except Exception as e:
        print(f"Error loading 'bank_data.json': {e}. Initializing 'bank_data' as empty.")
        bank_data = {}
elif not isinstance(globals()['bank_data'], dict):
    print("Warning: 'bank_data' found but is not a dictionary. Initializing 'bank_data' as empty.")
    bank_data = {}
else:
    bank_data = globals()['bank_data']

df = pd.DataFrame.from_dict(bank_data, orient='index')
df.reset_index(inplace=True)
df.rename(columns={'index': 'Account_ID'}, inplace=True)

df.to_csv('banking_data.csv', index=False)
print("Data exported successfully as 'banking_data.csv'")

from google.colab import drive
drive.mount('/content/drive')
df.to_csv('/content/drive/MyDrive/banking_data.csv', index=False)

































import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

df = pd.DataFrame.from_dict(bank_data, orient='index')
df.reset_index(inplace=True)
df.rename(columns={'index': 'Account_ID'}, inplace=True)

df.to_csv('/content/drive/MyDrive/banking_data_powerbi.csv', index=False)

print("Data exported successfully!")
print(f"Total Records: {len(df)}")
print(f"File saved at: /content/drive/MyDrive/banking_data_powerbi.csv")
print("\nData Preview:")
print(df.head())